---
version: "3.8"
services:
  movies:
    image: sudhar1998/moviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: sudhar1998/trainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: sudhar1998/dthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: sudhar1998/rechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
